### ISSUE TITLE
Does not function in Django 4.0

### ISSUE THREAD

**Issue by JosiahDub** [neutronX/django-markdownx#213]
As of Django 4.0, `django.conf.urls.url` has been deprecated in favor of `django.urls.re_path`. MardownX URLs will have to change to work in Django 4.0.

**Comment by JosiahDub** [comment]
Realized this has been updated, but not released. My bad.

**Comment by cafischer** [comment]
Using the current version v3.0.1. I still get the error (ImportError: cannot import name 'url' from 'django.conf.urls'). When will this be released?
